import { fileURLToPath } from "node:url"

import { defineConfig } from "vitest/config"

const projectRoot = fileURLToPath(new URL(".", import.meta.url))

export default defineConfig({
  resolve: {
    alias: { "@": projectRoot },
  },
  test: {
    environment: "node",
    globalSetup: ["./vitest.global-setup.ts"],
    setupFiles: ["./vitest.setup.ts"],
    include: ["**/*.test.ts", "**/*.test.tsx"],
    exclude: ["node_modules/**", ".next/**"],
    // Vitest only defaults NODE_ENV, so pin it: @next/env picks .env.test from it.
    env: { NODE_ENV: "test" },
    // Integration tests share one database, so keep test files sequential.
    fileParallelism: false,
    coverage: {
      provider: "v8",
      include: [
        "app/**/*.{ts,tsx}",
        "db/**/*.ts",
        "lib/**/*.ts",
        "scripts/**/*.ts",
        "shared/**/*.ts",
      ],
      exclude: [
        "**/__tests__/**",
        "db/migrations/**",
        // Generated by the shadcn scaffold.
        "lib/utils.ts",
        // Server Components, exercised in the browser rather than in vitest.
        "app/**/page.tsx",
        "app/**/layout.tsx",
        // Thin argv/stdout wrapper around the tested module beside it.
        "scripts/*.cli.ts",
      ],
      thresholds: { lines: 80, functions: 80, branches: 80, statements: 80 },
    },
  },
})
